### ISSUE TITLE
Update the entrypoint for the image to handle renewals

### ISSUE THREAD

**Issue by alegradi** [ukfast/certbot-dns-safedns#10]
### What is the issue?

At present this docker image is unable to handle renewals for SSL. This is due to the current entrypoint:

```
ENTRYPOINT ["certbot", "certonly", "--authenticator", "certbot-dns-safedns:dns_safedns", "--certbot-dns-safedns:dns_safedns-credentials", "/safedns.ini"]
```

### Steps To Reproduce

```
# docker run -it -v ~/.config/letsencrypt:/root/.config/letsencrypt -v /etc/letsencrypt:/etc/letsencrypt -v /var/lib/letsencrypt:/var/lib/letsencrypt ukfast/certbot-dns-safedns:latest --certbot-dns-safedns:dns_safedns-credentials ~/.config/letsencrypt/safedns.ini renew
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: renew
```

### Expected behaviour

We should be able to utilize the certbot command's subcommands like: `renew`, `certificates`, `delete` etc 

### Possible fixes

Modify the Entrypoint

**Comment by miff2000** [comment]
Ahh, looks like this was changed to be `certonly` some time back
* https://github.com/ukfast/certbot-dns-safedns/commit/533da667df43eed11b0dba6e915c20188b7c6021#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557
